version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: tupi-games-mysql
    restart: always
    environment:
      MYSQL_DATABASE: tupi-games
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tupi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tupi-games-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - tupi-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tupi-games-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tupi-network

volumes:
  mysql_data:

networks:
  tupi-network:
    driver: bridge
